### ISSUE TITLE
Migrating this Repository to Voxpupuli

### ISSUE THREAD

**Issue by SimonHoenscheid** [voxpupuli/puppet-catalog-diff#60]
Hi Camptocamp Staff, 

Voxpupuli is interested in adopting this repository and maintain the software. 
@yann-soubeyrand and @ckaenzig Raphaël Pinson metioned you might be the right people to ping.

Kind Regards,
Simon

**Comment by DLeich** [comment]
Considering the lack of response on a few of the pull requests currently open, I'm wondering if it would just be better to fork the repo instead.  I'd be happy to just open new PR's with a fork under Voxpupuli if that situation occurs.

**Comment by bastelfreak** [comment]
@saimonn hi! Is that something you could help us with?

**Comment by saimonn** [comment]
Hello, I'll ping the team internally for approval, I guess there should be no problem.

**Comment by saimonn** [comment]
Ok, let's go with the transfer. I would need repo creation permissions to transfer directly to voxpupuli. @bastelfreak should I transfer the ownership to your personal github account and let you transfer it again to voxpupuli  ?

**Comment by bastelfreak** [comment]
great to hear! I sent you an invitation to Vox Pupuli. Once you accept that you can directly migrate it to there. Do you also want to migrate https://github.com/camptocamp/puppet-catalog-diff-viewer?

You just need to do the repo migration, we will take care of the further permission setup. Do you have any team members that would like to keep access/stay involved in the project? I'm happy to invite them as well.

**Comment by bastelfreak** [comment]
thanks for the quick response. I will close the issue for now. If there are more people that need access just ping me.
